M48
; DRILL file KiCad 10.0.0 date 2026-04-10T19:54:21
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-10T19:54:21-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.500
%
G90
G05
T1
X137.5Y-99.0
X145.5Y-89.65
T2
X132.5Y-89.5
X132.5Y-96.0
X149.5Y-89.5
X149.5Y-95.5
M30
